[build]
  command = "npm run build"
  functions = "functions"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5000
  publish = "build"
